server {
    listen 8081;
    listen [::]:8081;

    server_name _;

    root /usr/share/phpmyadmin;
    index index.php index.html;
    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    access_log off;
    error_log  /var/log/nginx/phpmyadmin.app-error.log error;

    client_max_body_size 100m;
    client_body_timeout 120s;

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:<php_socket>;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTP_PROXY "";
        fastcgi_read_timeout 300;
    }

    location ~ /\.ht {
        deny all;
    }
}
